//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.ServiceReference12 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientIdVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PatientIdVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private IdType typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IdType type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdType", Namespace="http://tempuri.org/")]
    public enum IdType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PESEL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDENTITY_CARD = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOTHER_PESEL = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOTHER_IDENTITY_CARD = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientWithOrderListVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PatientWithOrderListVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PatientVO patientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrderVO[] ordersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PatientVO patient {
            get {
                return this.patientField;
            }
            set {
                if ((object.ReferenceEquals(this.patientField, value) != true)) {
                    this.patientField = value;
                    this.RaisePropertyChanged("patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public OrderVO[] orders {
            get {
                return this.ordersField;
            }
            set {
                if ((object.ReferenceEquals(this.ordersField, value) != true)) {
                    this.ordersField = value;
                    this.RaisePropertyChanged("orders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PatientVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PatientIdVO patientIdVOField;
        
        private System.DateTime birthDateField;
        
        private Gender genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fatherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddressVO addressField;
        
        private long hciPrivateKeyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string secondName {
            get {
                return this.secondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.secondNameField, value) != true)) {
                    this.secondNameField = value;
                    this.RaisePropertyChanged("secondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PatientIdVO patientIdVO {
            get {
                return this.patientIdVOField;
            }
            set {
                if ((object.ReferenceEquals(this.patientIdVOField, value) != true)) {
                    this.patientIdVOField = value;
                    this.RaisePropertyChanged("patientIdVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                if ((this.birthDateField.Equals(value) != true)) {
                    this.birthDateField = value;
                    this.RaisePropertyChanged("birthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public Gender gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fatherName {
            get {
                return this.fatherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fatherNameField, value) != true)) {
                    this.fatherNameField = value;
                    this.RaisePropertyChanged("fatherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public AddressVO address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long hciPrivateKeyId {
            get {
                return this.hciPrivateKeyIdField;
            }
            set {
                if ((this.hciPrivateKeyIdField.Equals(value) != true)) {
                    this.hciPrivateKeyIdField = value;
                    this.RaisePropertyChanged("hciPrivateKeyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ContractorVO contractorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExaminationVO[] examinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoctorVO doctorField;
        
        private System.DateTime orderTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valuableClinicInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpecimenCollectionVO specimenCollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ContractorVO contractor {
            get {
                return this.contractorField;
            }
            set {
                if ((object.ReferenceEquals(this.contractorField, value) != true)) {
                    this.contractorField = value;
                    this.RaisePropertyChanged("contractor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ExaminationVO[] examination {
            get {
                return this.examinationField;
            }
            set {
                if ((object.ReferenceEquals(this.examinationField, value) != true)) {
                    this.examinationField = value;
                    this.RaisePropertyChanged("examination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public DoctorVO doctor {
            get {
                return this.doctorField;
            }
            set {
                if ((object.ReferenceEquals(this.doctorField, value) != true)) {
                    this.doctorField = value;
                    this.RaisePropertyChanged("doctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime orderTime {
            get {
                return this.orderTimeField;
            }
            set {
                if ((this.orderTimeField.Equals(value) != true)) {
                    this.orderTimeField = value;
                    this.RaisePropertyChanged("orderTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string valuableClinicInfo {
            get {
                return this.valuableClinicInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.valuableClinicInfoField, value) != true)) {
                    this.valuableClinicInfoField = value;
                    this.RaisePropertyChanged("valuableClinicInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public SpecimenCollectionVO specimenCollection {
            get {
                return this.specimenCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.specimenCollectionField, value) != true)) {
                    this.specimenCollectionField = value;
                    this.RaisePropertyChanged("specimenCollection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AddressVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        private int codeTerytField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string houseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apartamentNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                if ((object.ReferenceEquals(this.streetField, value) != true)) {
                    this.streetField = value;
                    this.RaisePropertyChanged("street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postcodeField, value) != true)) {
                    this.postcodeField = value;
                    this.RaisePropertyChanged("postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int codeTeryt {
            get {
                return this.codeTerytField;
            }
            set {
                if ((this.codeTerytField.Equals(value) != true)) {
                    this.codeTerytField = value;
                    this.RaisePropertyChanged("codeTeryt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string houseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.houseNumberField, value) != true)) {
                    this.houseNumberField = value;
                    this.RaisePropertyChanged("houseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apartamentNumber {
            get {
                return this.apartamentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.apartamentNumberField, value) != true)) {
                    this.apartamentNumberField = value;
                    this.RaisePropertyChanged("apartamentNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://tempuri.org/")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        K = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        N = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractorVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ContractorVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string regonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AddressVO addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string institutionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string regon {
            get {
                return this.regonField;
            }
            set {
                if ((object.ReferenceEquals(this.regonField, value) != true)) {
                    this.regonField = value;
                    this.RaisePropertyChanged("regon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AddressVO address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string institutionId {
            get {
                return this.institutionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.institutionIdField, value) != true)) {
                    this.institutionIdField = value;
                    this.RaisePropertyChanged("institutionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctorVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DoctorVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pzwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpecializationVO[] specializationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string secondName {
            get {
                return this.secondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.secondNameField, value) != true)) {
                    this.secondNameField = value;
                    this.RaisePropertyChanged("secondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pzw {
            get {
                return this.pzwField;
            }
            set {
                if ((object.ReferenceEquals(this.pzwField, value) != true)) {
                    this.pzwField = value;
                    this.RaisePropertyChanged("pzw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SpecializationVO[] specializations {
            get {
                return this.specializationsField;
            }
            set {
                if ((object.ReferenceEquals(this.specializationsField, value) != true)) {
                    this.specializationsField = value;
                    this.RaisePropertyChanged("specializations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecimenCollectionVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SpecimenCollectionVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lotNumberField;
        
        private System.DateTime collectionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MedicalStaffVO collectedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ContractorVO institutionField;
        
        private int dzmField;
        
        private double weightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.lotNumberField, value) != true)) {
                    this.lotNumberField = value;
                    this.RaisePropertyChanged("lotNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime collectionTime {
            get {
                return this.collectionTimeField;
            }
            set {
                if ((this.collectionTimeField.Equals(value) != true)) {
                    this.collectionTimeField = value;
                    this.RaisePropertyChanged("collectionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MedicalStaffVO collectedBy {
            get {
                return this.collectedByField;
            }
            set {
                if ((object.ReferenceEquals(this.collectedByField, value) != true)) {
                    this.collectedByField = value;
                    this.RaisePropertyChanged("collectedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ContractorVO institution {
            get {
                return this.institutionField;
            }
            set {
                if ((object.ReferenceEquals(this.institutionField, value) != true)) {
                    this.institutionField = value;
                    this.RaisePropertyChanged("institution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int dzm {
            get {
                return this.dzmField;
            }
            set {
                if ((this.dzmField.Equals(value) != true)) {
                    this.dzmField = value;
                    this.RaisePropertyChanged("dzm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExaminationVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExaminationVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        private PriorytetType priorytetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rateField;
        
        private bool specimenCollectedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public PriorytetType priorytet {
            get {
                return this.priorytetField;
            }
            set {
                if ((this.priorytetField.Equals(value) != true)) {
                    this.priorytetField = value;
                    this.RaisePropertyChanged("priorytet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rate {
            get {
                return this.rateField;
            }
            set {
                if ((object.ReferenceEquals(this.rateField, value) != true)) {
                    this.rateField = value;
                    this.RaisePropertyChanged("rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool specimenCollected {
            get {
                return this.specimenCollectedField;
            }
            set {
                if ((this.specimenCollectedField.Equals(value) != true)) {
                    this.specimenCollectedField = value;
                    this.RaisePropertyChanged("specimenCollected");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriorytetType", Namespace="http://tempuri.org/")]
    public enum PriorytetType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUTYNOWE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CITO = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecializationVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SpecializationVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string specializationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string specializationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string specializationCode {
            get {
                return this.specializationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.specializationCodeField, value) != true)) {
                    this.specializationCodeField = value;
                    this.RaisePropertyChanged("specializationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string specializationName {
            get {
                return this.specializationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.specializationNameField, value) != true)) {
                    this.specializationNameField = value;
                    this.RaisePropertyChanged("specializationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalStaffVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MedicalStaffVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pzwField;
        
        private ProfessionType typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string secondName {
            get {
                return this.secondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.secondNameField, value) != true)) {
                    this.secondNameField = value;
                    this.RaisePropertyChanged("secondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pzw {
            get {
                return this.pzwField;
            }
            set {
                if ((object.ReferenceEquals(this.pzwField, value) != true)) {
                    this.pzwField = value;
                    this.RaisePropertyChanged("pzw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ProfessionType type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfessionType", Namespace="http://tempuri.org/")]
    public enum ProfessionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCTOR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NURSE = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference12.ELIWebServiceSoap")]
    public interface ELIWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name param from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HelloWorldResponse HelloWorld(HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWorldResponse> HelloWorldAsync(HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name patientIdVO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPatientWithOrderListBy", ReplyAction="*")]
        getPatientWithOrderListByResponse getPatientWithOrderListBy(getPatientWithOrderListByRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPatientWithOrderListBy", ReplyAction="*")]
        System.Threading.Tasks.Task<getPatientWithOrderListByResponse> getPatientWithOrderListByAsync(getPatientWithOrderListByRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPatientWithOrderListByRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPatientWithOrderListBy", Namespace="http://tempuri.org/", Order=0)]
        public getPatientWithOrderListByRequestBody Body;
        
        public getPatientWithOrderListByRequest() {
        }
        
        public getPatientWithOrderListByRequest(getPatientWithOrderListByRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPatientWithOrderListByRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PatientIdVO patientIdVO;
        
        public getPatientWithOrderListByRequestBody() {
        }
        
        public getPatientWithOrderListByRequestBody(PatientIdVO patientIdVO) {
            this.patientIdVO = patientIdVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPatientWithOrderListByResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPatientWithOrderListByResponse", Namespace="http://tempuri.org/", Order=0)]
        public getPatientWithOrderListByResponseBody Body;
        
        public getPatientWithOrderListByResponse() {
        }
        
        public getPatientWithOrderListByResponse(getPatientWithOrderListByResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPatientWithOrderListByResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PatientWithOrderListVO getPatientWithOrderListByResult;
        
        public getPatientWithOrderListByResponseBody() {
        }
        
        public getPatientWithOrderListByResponseBody(PatientWithOrderListVO getPatientWithOrderListByResult) {
            this.getPatientWithOrderListByResult = getPatientWithOrderListByResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ELIWebServiceSoapChannel : ELIWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ELIWebServiceSoapClient : System.ServiceModel.ClientBase<ELIWebServiceSoap>, ELIWebServiceSoap {
        
        public ELIWebServiceSoapClient() {
        }
        
        public ELIWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ELIWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ELIWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ELIWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWorldResponse ELIWebServiceSoap.HelloWorld(HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string param) {
            HelloWorldRequest inValue = new HelloWorldRequest();
            inValue.Body = new HelloWorldRequestBody();
            inValue.Body.param = param;
            HelloWorldResponse retVal = ((ELIWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWorldResponse> ELIWebServiceSoap.HelloWorldAsync(HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWorldResponse> HelloWorldAsync(string param) {
            HelloWorldRequest inValue = new HelloWorldRequest();
            inValue.Body = new HelloWorldRequestBody();
            inValue.Body.param = param;
            return ((ELIWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getPatientWithOrderListByResponse ELIWebServiceSoap.getPatientWithOrderListBy(getPatientWithOrderListByRequest request) {
            return base.Channel.getPatientWithOrderListBy(request);
        }
        
        public PatientWithOrderListVO getPatientWithOrderListBy(PatientIdVO patientIdVO) {
            getPatientWithOrderListByRequest inValue = new getPatientWithOrderListByRequest();
            inValue.Body = new getPatientWithOrderListByRequestBody();
            inValue.Body.patientIdVO = patientIdVO;
            getPatientWithOrderListByResponse retVal = ((ELIWebServiceSoap)(this)).getPatientWithOrderListBy(inValue);
            return retVal.Body.getPatientWithOrderListByResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getPatientWithOrderListByResponse> ELIWebServiceSoap.getPatientWithOrderListByAsync(getPatientWithOrderListByRequest request) {
            return base.Channel.getPatientWithOrderListByAsync(request);
        }
        
        public System.Threading.Tasks.Task<getPatientWithOrderListByResponse> getPatientWithOrderListByAsync(PatientIdVO patientIdVO) {
            getPatientWithOrderListByRequest inValue = new getPatientWithOrderListByRequest();
            inValue.Body = new getPatientWithOrderListByRequestBody();
            inValue.Body.patientIdVO = patientIdVO;
            return ((ELIWebServiceSoap)(this)).getPatientWithOrderListByAsync(inValue);
        }
    }
}
